url: "https://www.gramkraxor.com"
baseurl: "/js"

title: "JS Toys"
author: "Gramkraxor"
jquery: "https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - html

collections:
  projects:
    output: true

defaults:
  -
    scope:
      path: ""
      type: projects
    values:
      layout: project
      permalink: /:name
