url: "https://gramkraxor.github.io"
baseurl: "/js"

title: "JS Toys"
author: "Gramkraxor"

exclude:
  - README.md
  - html

collections:
  projects:
    output: true

defaults:
  -
    scope:
      path: ""
      type: projects
    values:
      layout: project
      permalink: /:name
